<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="4" ignored="0" total="4" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Assertion Class Suite - Rediffmail" duration-ms="47949" started-at="2021-07-12T15:48:04 IST" finished-at="2021-07-12T15:48:52 IST">
    <groups>
    </groups>
    <test name="Rediffmail Form Test Case" duration-ms="17520" started-at="2021-07-12T15:48:04 IST" finished-at="2021-07-12T15:48:21 IST">
      <class name="TestCase.formRediffmail">
        <test-method status="FAIL" signature="FillingFormRediffmail(java.util.Hashtable)[pri:0, instance:TestCase.formRediffmail@394e1a0f]" name="FillingFormRediffmail" duration-ms="7347" started-at="2021-07-12T15:48:04 IST" data-provider="formData" finished-at="2021-07-12T15:48:11 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{PNumber=12345, MName=Sukla, RID=kaushikmukherjee2412, FName=Kaushik Mukherjee, Rpwd=test@1234, Pwd=test@1234, SQues=Music, Browser=Chrome}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Attribute value verification failed for for the attribute called class expected [countr] but found [country]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Attribute value verification failed for for the attribute called class expected [countr] but found [country]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at Utilities.Utils.AssertAttributeValue(Utils.java:657)
at TestCase.formRediffmail.FillingFormRediffmail(formRediffmail.java:318)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- FillingFormRediffmail -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:TestCase.formRediffmail@394e1a0f]" name="tearDown" is-config="true" duration-ms="836" started-at="2021-07-12T15:48:11 IST" finished-at="2021-07-12T15:48:12 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=FillingFormRediffmail status=FAILURE method=formRediffmail.FillingFormRediffmail(java.util.Hashtable)[pri:0, instance:TestCase.formRediffmail@394e1a0f] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="FAIL" signature="FillingFormRediffmail(java.util.Hashtable)[pri:0, instance:TestCase.formRediffmail@394e1a0f]" name="FillingFormRediffmail" duration-ms="8270" started-at="2021-07-12T15:48:12 IST" data-provider="formData" finished-at="2021-07-12T15:48:20 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{PNumber=45678, MName=Jenny, RID=SamMendes2412, FName=Sam Mendes, Rpwd=test@5678, Pwd=test@5678, SQues=Reading, Browser=Edge}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Attribute value verification failed for for the attribute called class expected [countr] but found [country]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Attribute value verification failed for for the attribute called class expected [countr] but found [country]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at Utilities.Utils.AssertAttributeValue(Utils.java:657)
at TestCase.formRediffmail.FillingFormRediffmail(formRediffmail.java:318)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- FillingFormRediffmail -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:TestCase.formRediffmail@394e1a0f]" name="tearDown" is-config="true" duration-ms="1011" started-at="2021-07-12T15:48:20 IST" finished-at="2021-07-12T15:48:21 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=FillingFormRediffmail status=FAILURE method=formRediffmail.FillingFormRediffmail(java.util.Hashtable)[pri:0, instance:TestCase.formRediffmail@394e1a0f] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- TestCase.formRediffmail -->
    </test> <!-- Rediffmail Form Test Case -->
    <test name="Rediffmail Compose Email Test Case" duration-ms="30398" started-at="2021-07-12T15:48:21 IST" finished-at="2021-07-12T15:48:52 IST">
      <class name="TestCase.SendingMailRediff">
        <test-method status="FAIL" signature="SendingEmailRediff(java.util.Hashtable)[pri:0, instance:TestCase.SendingMailRediff@26a7b76d]" name="SendingEmailRediff" duration-ms="13083" started-at="2021-07-12T15:48:21 IST" data-provider="sendMailData" finished-at="2021-07-12T15:48:34 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{CField=Test Mail Sent, Pwd=test@1234, UName=selenium.testmay2017, TField=kaushik.aryaan@gmail.com, SField=Test Mail, Browser=Chrome}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Text verification failed for for the text Logout expected [Logou] but found [Logout]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Text verification failed for for the text Logout expected [Logou] but found [Logout]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at Utilities.Utils.AssertText(Utils.java:529)
at TestCase.SendingMailRediff.SendingEmailRediff(SendingMailRediff.java:157)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SendingEmailRediff -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:TestCase.SendingMailRediff@26a7b76d]" name="tearDown" is-config="true" duration-ms="907" started-at="2021-07-12T15:48:34 IST" finished-at="2021-07-12T15:48:35 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=SendingEmailRediff status=FAILURE method=SendingMailRediff.SendingEmailRediff(java.util.Hashtable)[pri:0, instance:TestCase.SendingMailRediff@26a7b76d] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="FAIL" signature="SendingEmailRediff(java.util.Hashtable)[pri:0, instance:TestCase.SendingMailRediff@26a7b76d]" name="SendingEmailRediff" duration-ms="15276" started-at="2021-07-12T15:48:35 IST" data-provider="sendMailData" finished-at="2021-07-12T15:48:51 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{CField=Development Mail Sent, Pwd=test@1234, UName=selenium.testmay2017, TField=arundhoti.mukherjee@gmail.com, SField=Development Mail, Browser=Edge}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Text verification failed for for the text Logout expected [Logou] but found [Logout]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Text verification failed for for the text Logout expected [Logou] but found [Logout]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at Utilities.Utils.AssertText(Utils.java:529)
at TestCase.SendingMailRediff.SendingEmailRediff(SendingMailRediff.java:157)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SendingEmailRediff -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:TestCase.SendingMailRediff@26a7b76d]" name="tearDown" is-config="true" duration-ms="1113" started-at="2021-07-12T15:48:51 IST" finished-at="2021-07-12T15:48:52 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=SendingEmailRediff status=FAILURE method=SendingMailRediff.SendingEmailRediff(java.util.Hashtable)[pri:0, instance:TestCase.SendingMailRediff@26a7b76d] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- TestCase.SendingMailRediff -->
    </test> <!-- Rediffmail Compose Email Test Case -->
  </suite> <!-- Assertion Class Suite - Rediffmail -->
</testng-results>
